apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-demo.fullname" . }}
  labels:
    {{- include "helm-demo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      name: http
      nodePort: {{ .Values.service.nodePort }}
  selector:
    {{- include "helm-demo.selectorLabels" . | nindent 4 }}
